In [1]:
import pandas as pd
import os
from time import sleep
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains

from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
import urllib
import pathlib
import datetime

In [2]:
#Lets first connect to the web driver
CHROMEDRIVER_PATH =(r"C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
# Comman function for init driver
def init_driver(url):
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument('--disable-blink-features=AutomationControlled')
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    chrome_options.add_experimental_option('useAutomationExtension', False)
    
    pathlib.Path('download').mkdir(parents=True, exist_ok=True) 
    
    preferences = {
        "download.default_directory": os.getcwd() + os.path.sep + '/download',
    }

    chrome_options.add_experimental_option('prefs', preferences)

    driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH,options=chrome_options)
    driver.maximize_window()
    driver.get(url)
    return driver

In [4]:
def wait_for_page_load(xpath_url):
    try:
        element_present = EC.presence_of_element_located((By.XPATH, xpath_url))
        WebDriverWait(driver, 5).until(element_present)
    except TimeoutException:
        pass
    except NoSuchElementException:
        print("Element not found")

1. Scrape the details of most viewed videos on YouTube from Wikipedia: 
    Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details:
            
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [5]:
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'

In [6]:
driver = init_driver(url)

<ipython-input-3-cb6487642f59>:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH,options=chrome_options)

In [11]:

all_box = driver.find_elements_by_xpath('//div[@id="mw-content-text"]//table[@class="wikitable sortable jquery-tablesorter"]//tbody/tr')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [12]:
all_data = []
for one_box in all_box[:30]:
    rank = one_box.find_elements_by_xpath('.//td')[0].text
    name = one_box.find_elements_by_xpath('.//td')[1].text
    artist = one_box.find_elements_by_xpath('.//td')[2].text
    views = one_box.find_elements_by_xpath('.//td')[3].text
    upload_date = one_box.find_elements_by_xpath('.//td')[4].text
    
    all_data.append({
        'rank' : rank,
        'name' : name,
        'artist' : artist,
        'views' : views,
        'upload_date' : upload_date,
    })

df = pd.DataFrame(all_data)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,rank,name,artist,views,upload_date
0,1,"""Baby Shark Dance""[23]",Pinkfong Baby Shark - Kids' Songs & Stories,"9,453,134,982","June 17, 2016"
1,2,"""Despacito""[25]",Luis Fonsi,"7,572,747,360","January 12, 2017"
2,3,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"5,781,348,353","October 8, 2016"
3,4,"""Shape of You""[27]",Ed Sheeran,"5,483,427,541","January 30, 2017"
4,5,"""See You Again""[28]",Wiz Khalifa,"5,284,905,560","April 6, 2015"
5,6,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"4,549,294,432","May 2, 2018"
6,7,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"4,513,879,675 (as of Sep 29, 2021)","February 27, 2018"
7,8,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"4,461,096,975","January 31, 2012"
8,9,"""Uptown Funk""[34]",Mark Ronson,"4,319,159,452","November 19, 2014"
9,10,"""Phonics Song with Two Words""[35]",ChuChu TV,"4,220,180,419","March 6, 2014"
10,11,"""Gangnam Style""[36]",Psy,"4,211,421,413","July 15, 2012"
11,12,"""Dame Tu Cosita""[38]",El Chombo,"3,633,337,215","April 5, 2018"
12,13,"""Sugar""[39]",Maroon 5,"3,565,906,701","January 14, 2015"
13,14,"""Sorry""[40]",Justin Bieber,"3,474,094,697","October 22, 2015"
14,15,"""Roar""[41]",Katy Perry,"3,444,786,615","September 5, 2013"
15,16,"""Counting Stars""[42]",OneRepublic,"3,412,577,920","May 31, 2013"
16,17,"""Thinking Out Loud""[43]",Ed Sheeran,"3,337,279,340","October 7, 2014"
17,18,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"3,291,808,512","May 24, 2018"
18,19,"""Dark Horse""[45]",Katy Perry,"3,155,611,442","February 20, 2014"
19,20,"""Faded""[46]",Alan Walker,"3,155,489,927","December 3, 2015"
20,21,"""Girls Like You""[47]",Maroon 5,"3,143,116,042","May 31, 2018"
21,22,"""Lean On""[48]",Major Lazer,"3,105,926,931","March 22, 2015"
22,23,"""Bailando""[49]",Enrique Iglesias,"3,105,539,316","April 11, 2014"
23,24,"""Shake It Off""[50]",Taylor Swift,"3,104,230,107","August 18, 2014"
24,25,"""Let Her Go""[51]",Passenger,"3,090,217,295","July 25, 2012"
25,26,"""Axel F""[52]",Crazy Frog,"3,035,828,739","June 17, 2009"
26,27,"""Mi Gente""[53]",J Balvin,"2,986,493,839","June 29, 2017"
27,28,"""Perfect""[54]",Ed Sheeran,"2,974,982,274","November 9, 2017"
28,29,"""Waka Waka (This Time for Africa)""[55]",Shakira,"2,962,613,841","June 4, 2010"
29,30,"""Hello""[56]",Adele,"2,889,107,727","October 23, 2015"

2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details:
A) Match title (I.e. 1 st ODI)
B) Series
C) Place
D) Date
E) Time ###### Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [13]:
driver.get('https://www.bcci.tv/')

In [14]:
driver.find_element_by_xpath('//div[contains(@class,"navigation__drop-down")]').click()
driver.find_element_by_xpath('//a[contains(text(),"Fixtures")]').click()

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [15]:
driver.find_element_by_xpath('//button[contains(@class,"js-show-more-button")]').click()
sleep(5)

In [16]:

all_box = driver.find_elements_by_xpath('//div[@class="event-list__list"]//a')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [17]:
sleep(5)

In [18]:
all_list = []
driver.find_element_by_xpath('//body').send_keys(Keys.CONTROL + Keys.HOME)
for one_box in all_box:
    sleep(1)
    date_time = one_box.find_element_by_xpath('.//div[@class="fixture__full-date"]')
    date = date_time.find_elements_by_xpath('.//span')[0].text
    month = date_time.find_elements_by_xpath('.//span')[1].text
    time = date_time.find_elements_by_xpath('.//span')[2].text
    
    match_title = one_box.find_element_by_xpath('.//div[contains(@class,"fixture__info")]//span[contains(@class,"fixture__format")]').text
    series = one_box.find_element_by_xpath('.//div[contains(@class,"fixture__info")]//span[contains(@class,"fixture__tournament-label")]').text
    place = one_box.find_element_by_xpath('.//div[contains(@class,"fixture__description")]//p/span').text
    date = date + ' ' + month
    time = time

    
    all_list.append({
        'match_title': match_title,
        'series': series,
        'place': place,
        'date': date,
        'time': time,

    })
    
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:392: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,match_title,series,place,date,time
0,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",24 OCTOBER,19:30 IST
1,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",31 OCTOBER,19:30 IST
2,T20I,2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",03 NOVEMBER,19:30 IST
3,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",05 NOVEMBER,19:30 IST
4,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",08 NOVEMBER,19:30 IST
5,T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",17 NOVEMBER,19:00 IST
6,T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",19 NOVEMBER,19:00 IST
7,T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",21 NOVEMBER,19:00 IST
8,TEST,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",25 NOVEMBER,09:30 IST
9,TEST,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",03 DECEMBER,09:30 IST
10,TEST,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",17 DECEMBER,13:30 IST
11,TEST,SOUTH AFRICA V INDIA 2021/2022,"Supersport Park, Centurion",26 DECEMBER,13:30 IST
12,TEST,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",03 JANUARY,13:30 IST
13,ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",11 JANUARY,14:00 IST
14,ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",14 JANUARY,14:00 IST
15,ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",16 JANUARY,14:00 IST
16,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",19 JANUARY,19:30 IST
17,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",21 JANUARY,19:30 IST
18,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",23 JANUARY,19:30 IST
19,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",26 JANUARY,19:30 IST
20,ODI,INDIA V WEST INDIES 2022,"Narendra Modi Stadium, Ahmedabad",06 FEBRUARY,13:00 IST
21,ODI,INDIA V WEST INDIES 2022,"Sawai Mansingh Stadium, Jaipur",09 FEBRUARY,13:00 IST
22,ODI,INDIA V WEST INDIES 2022,"Eden Gardens, Kolkata",12 FEBRUARY,13:00 IST
23,T20I,INDIA V WEST INDIES 2022,"Barabati Stadium, Cuttack",15 FEBRUARY,19:00 IST
24,T20I,INDIA V WEST INDIES 2022,"ACA-VDCA Stadium, Visakhapatnam",18 FEBRUARY,19:00 IST
25,T20I,INDIA V WEST INDIES 2022,"Greenfield Stadium, Thiruvananthapuram",20 FEBRUARY,19:00 IST
26,TEST,INDIA V SRI LANKA 2022,"M.Chinnaswamy Stadium, Bangalore",25 FEBRUARY,09:30 IST
27,TEST,INDIA V SRI LANKA 2022,"Punjab Cricket Association Stadium, Mohali, Ch...",05 MARCH,09:30 IST
28,T20I,INDIA V SRI LANKA 2022,"Punjab Cricket Association Stadium, Mohali, Ch...",13 MARCH,19:00 IST
29,T20I,INDIA V SRI LANKA 2022,"Himachal Pradesh Cricket Association Stadium, ...",15 MARCH,19:00 IST
30,T20I,INDIA V SRI LANKA 2022,Bharat Ratna Shri Atal Bihari Vajpai Ekana Cri...,18 MARCH,19:00 IST
31,T20I,INDIA V SOUTH AFRICA 2022,"M. A. Chidambaram Stadium, Chennai",09 JUNE,19:00 IST
32,T20I,INDIA V SOUTH AFRICA 2022,"M.Chinnaswamy Stadium, Bangalore",12 JUNE,19:00 IST
33,T20I,INDIA V SOUTH AFRICA 2022,"Vidarbha Cricket Association Stadium, Nagpur",14 JUNE,19:00 IST
34,T20I,INDIA V SOUTH AFRICA 2022,"Saurashtra Cricket Association Stadium, Rajkot",17 JUNE,19:00 IST
35,T20I,INDIA V SOUTH AFRICA 2022,"Arun Jaitley Stadium, Delhi",19 JUNE,19:00 IST
36,T20I,ENGLAND V INDIA 2022,"Old Trafford, Manchester",01 JULY,23:00 IST
37,T20I,ENGLAND V INDIA 2022,"Trent Bridge, Nottingham",03 JULY,19:00 IST
38,T20I,ENGLAND V INDIA 2022,"The Ageas Bowl, Southampton",06 JULY,23:00 IST
39,ODI,ENGLAND V INDIA 2022,"Edgbaston, Birmingham",09 JULY,15:30 IST

3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:

A) Name
B) Description ###### Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [19]:
driver.get('https://www.guru99.com')

In [20]:
driver.find_element_by_xpath('//a[@title="Selenium"]').click()

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [21]:
driver.find_element_by_xpath('//a[@data-lasso-id="182688"]').click()

In [22]:
all_box = driver.find_elements_by_xpath('//table/tbody/tr')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [23]:
all_list = []
for i, one_box in enumerate(all_box):
    if i == 0 :
        continue
        
    name = one_box.find_elements_by_xpath('.//td')[0].text
    description = one_box.find_elements_by_xpath('.//td')[1].text
    
    all_list.append({
        'name': name,
        'description': description
    })
    
        
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,name,description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details:
Rank
State
GSDP at current price (19-20)
GSDP at current price (18-19)
Share(18-19)
GDP($ billion) ##### Note: - From statisticstimes home page you have to reach to economy page through code.

In [32]:
driver.get('https://statisticstimes.com/')

In [33]:
drop_down_element = driver.find_element_by_xpath('//button[contains(text(),"Economy")]')

In [34]:
# Hovering 
ActionChains(driver).move_to_element(drop_down_element).perform()

In [35]:
driver.find_element_by_xpath('//div[@class="dropdown-content"]/a[@href="economy/india-statistics.php"]').click()

In [36]:
driver.find_element_by_xpath('//a[contains(text(),"GDP of Indian states")]').click()

In [37]:
all_boxes = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [38]:
all_data = []
for one_box in all_boxes:
    
    rank = one_box.find_elements_by_xpath('.//td')[0].text
    state = one_box.find_elements_by_xpath('.//td')[1].text
    gsdp_at_current_price_19_20_ = one_box.find_elements_by_xpath('.//td')[2].text
    gsdp_at_current_price_18_19 = one_box.find_elements_by_xpath('.//td')[3].text
    share_18_19 = one_box.find_elements_by_xpath('.//td')[4].text
    gdp_billion = one_box.find_elements_by_xpath('.//td')[5].text

    all_data.append({
        'rank': rank,
        'state': state,
        'gsdp_at_current_price_19_20_': gsdp_at_current_price_19_20_,
        'gsdp_at_current_price_18_19': gsdp_at_current_price_18_19,
        'share_18_19': share_18_19,
        'gdp_billion': gdp_billion,
    })
    
df = pd.DataFrame(all_data)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,rank,state,gsdp_at_current_price_19_20_,gsdp_at_current_price_18_19,share_18_19,gdp_billion
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

5. Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:

A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [39]:

driver.get('https://github.com/trending')

In [40]:
all_box_url = driver.find_elements_by_xpath('//article/h1/a')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [41]:
all_urls = []
for one_url in all_box_url:
    all_urls.append(one_url.get_attribute('href'))

In [42]:
all_data = []
for one_url in all_urls:
    
    driver.get(one_url)

    repository_title = driver.find_element_by_xpath('//h1/strong').text
    if len(driver.find_elements_by_xpath('//div[@class="BorderGrid-cell"]/p')) != 0:
        repository_description = driver.find_element_by_xpath('//div[@class="BorderGrid-cell"]/p').text
    else:
        repository_description = 'NA'
    
    if len(driver.find_elements_by_xpath('//div[@class="BorderGrid-cell"]//a[contains(text(),"Contributors")]/span[@class="Counter"]')) != 0:
        contributors_count = driver.find_element_by_xpath('//div[@class="BorderGrid-cell"]//a[contains(text(),"Contributors")]/span[@class="Counter"]').text
    else:
        contributors_count = 'NA'
        
    languages_used_elemens = driver.find_elements_by_xpath('//a[contains(@data-ga-click,"Repository, language")]')
    
    language_used = []
    for lang in languages_used_elemens:
        language_used.append(lang.text.split('\n')[0])

    all_data.append({
        'repository_title': repository_title,
        'repository_description': repository_description,
        'contributors_count': contributors_count,
        'language_used': ', '.join(language_used),
    })
    
    
df = pd.DataFrame(all_data)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

,repository_title,repository_description,contributors_count,language_used
0,Dummy-Robot,我的超迷你机械臂机器人项目。,NA,
1,algo,Set up a personal VPN in the cloud,156,"Python, Jinja, Shell"
2,JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,260,Java
3,uptime-kuma,A fancy self-hosted monitoring tool,63,"JavaScript, Vue, SCSS, Shell, TypeScript, Dock..."
4,vue-next,"🖖 Vue.js is a progressive, incrementally-adopt...",280,"TypeScript, HTML, JavaScript"
5,MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,10,"JavaScript, Python, HTML"
6,flipper,A desktop debugging platform for mobile develo...,219,"TypeScript, Java, Ruby, Objective-C++, C++, Ob..."
7,frp,A fast reverse proxy to help you expose a loca...,72,"Go, Vue, JavaScript, Shell, HTML, Makefile, Less"
8,srs,"SRS is a simple, high efficiency and realtime ...",64,"C++, JavaScript, ActionScript, HTML, Shell, Py..."
9,awesome-python,"A curated list of awesome Python frameworks, l...",392,"Python, Makefile"
10,yt-dlp,A youtube-dl fork with additional features and...,854,Python
11,clean-dns-bpf,基于 Rust + eBPF 丢弃 GFW DNS 污染包,NA,Rust
12,awesome-actions,A curated list of awesome actions to use on Gi...,280,
13,Awesome-Hacking,A collection of various awesome lists for hack...,21,
14,vue-vben-admin,"A modern vue admin. It is based on Vue3, vite ...",72,"Vue, TypeScript, Less, JavaScript, CSS, HTML"
15,Python_and_the_Web,"Build Bots, Scrape a website or use an API to ...",102,"Python, TeX, HTML"
16,quickemu,"Quickly create and run optimised Windows, macO...",16,"Shell, Python"
17,dos-like,"Engine for making things with a MS-DOS feel, b...",3,C
18,rocketmq,Mirror of Apache RocketMQ,280,Java
19,WebFirst,.NET CORE 代码生成器 ，Web中使用CodeFirst模式， 实体生成器，UI代码...,NA,"C#, CSS, HTML"
20,flta-materials,The projects and the materials that accompany ...,8,"Dart, Ruby, Swift, HTML, Kotlin, Shell, Object..."
21,CTO,Call Tree Overviewer,NA,Python
22,Sentinel,A powerful flow control component enabling rel...,152,"Java, JavaScript, HTML, CSS, Shell, Dockerfile"
23,spring-cloud-alibaba,Spring Cloud Alibaba provides a one-stop solut...,114,Java
24,vue,"🖖 Vue.js is a progressive, incrementally-adopt...",401,JavaScript


6. Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/ You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board ##### Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [43]:
driver.get('https://www.billboard.com')

In [44]:
driver.find_element_by_xpath('//li[@class="header__subnav__item"]/a[text()="Hot 100"]').click()

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [45]:
all_boxes = driver.find_elements_by_xpath('//li[contains(@class,"list__element")]/button')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [46]:
all_list = []
for one_box in all_boxes:

    song_name = one_box.find_element_by_xpath('.//span[contains(@class,"chart-element__information__song")]').text
    artist_name = one_box.find_element_by_xpath('.//span[contains(@class,"chart-element__information__artist")]').text
    last_week_rank = one_box.find_element_by_xpath('.//span[contains(@class,"text--last")]').get_attribute('innerHTML')
    peak_rank = one_box.find_element_by_xpath('.//span[contains(@class,"text--peak")]').get_attribute('innerHTML')
    weeks_on_board = one_box.find_element_by_xpath('.//span[contains(@class,"text--week")]').get_attribute('innerHTML')


    all_list.append({
        'song_name': song_name,
        'artist_name': artist_name,
        'last_week_rank': last_week_rank,
        'peak_rank': peak_rank,
        'weeks_on_board': weeks_on_board,
    })
    
    
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:392: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

,song_name,artist_name,last_week_rank,peak_rank,weeks_on_board
0,My Universe,Coldplay x BTS,,1 Pk,1 WoC
1,Stay,The Kid LAROI & Justin Bieber,1 LW,1 Pk,12 WoC
2,Industry Baby,Lil Nas X & Jack Harlow,2 LW,2 Pk,10 WoC
3,Way 2 Sexy,Drake Featuring Future & Young Thug,3 LW,1 Pk,4 WoC
4,Fancy Like,Walker Hayes,5 LW,5 Pk,15 WoC
...,...,...,...,...,...
95,Pipe Down,Drake,68 LW,14 Pk,4 WoC
96,Papi's Home,Drake,66 LW,8 Pk,4 WoC
97,Chosen,Blxst & Tyga Featuring Ty Dolla $ign,,98 Pk,1 WoC
98,Toxic Punk,YoungBoy Never Broke Again,,99 Pk,1 WoC
99,Moon,Kanye West,76 LW,17 Pk,5 WoC

7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location ##### Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [47]:
driver.get('https://www.naukri.com/')

In [48]:
url = driver.find_element_by_xpath('//a[@title="Search Recruiters"]').get_attribute('href')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [49]:
driver.get(url)

In [50]:
driver.find_element_by_xpath('//input[@class="sugInp"]').send_keys('Data science')

In [51]:
driver.find_element_by_xpath('//button[@id="qsbFormBtn"]').click()

In [52]:
all_list = []


while True:
    
    all_boxes = driver.find_elements_by_xpath('//div[@class="recInfo"]')
    for one_box in all_boxes:

        name = one_box.find_elements_by_xpath('.//a[@class="ellipsis"]')[0].text
        designation = one_box.find_element_by_xpath('.//span[@class="ellipsis clr"]').text
        company = one_box.find_elements_by_xpath('.//a[@class="ellipsis"]')[1].text
        skills_they_hire_for = one_box.find_element_by_xpath('.//div[@class="hireSec highlightable"]').text

        if len(one_box.find_elements_by_xpath('.//small[@class="ellipsis"]')) !=0:
            location = one_box.find_element_by_xpath('.//small[@class="ellipsis"]').text
        else:
            location = ''



        all_list.append({
            'name' : name,
            'designation' : designation,
            'company' : company,
            'skills_they_hire_for' : skills_they_hire_for,
            'location' : location,
        })
            
    if len(driver.find_elements_by_xpath('//div[@class="pagination"]/button[text()="Next"]')) != 0:
        driver.find_element_by_xpath('//div[@class="pagination"]/button[text()="Next"]').click()
    else:
        break
        
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:392: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

,name,designation,company,skills_they_hire_for,location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Hyderabad / Secunderabad
...,...,...,...,...,...
5936,Vikas Tiwari,Tester,Accenture,"Epicor Pos, C++, Sql, Plsql, Sap, Pos",Mumbai
5937,Faraaz Kharwa,Senior Manager,Netscribes (India) Pvt Ltd,Not Specified,Kolkata
5938,Ravi Manda,Sr. Talent Acquisition Recruiter,New York Global Consultants Pvt. Ltd.,Not Specified,Hyderabad / Secunderabad
5939,Ashish Dave,Sales Head-APAC,Cloudiway,Not Specified,Delhi
5940,Praveen Kumar,Lead Executive,Aricent Technologies (H) Limited,Not Specified,Bengaluru / Bangalore

In [53]:
df.to_csv('all_recurat_naukari.csv')

8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/ You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [54]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [55]:
all_box = driver.find_elements_by_xpath('//tbody/tr')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [56]:
all_list = []

for one_box in all_box:
    
    book_name = one_box.find_elements_by_xpath('.//td')[1].text
    author_name = one_box.find_elements_by_xpath('.//td')[2].text
    volumes_sold = one_box.find_elements_by_xpath('.//td')[3].text
    publisher = one_box.find_elements_by_xpath('.//td')[4].text
    genre = one_box.find_elements_by_xpath('.//td')[5].text

    all_list.append({
        'book_name': book_name,
        'author_name': author_name,
        'volumes_sold': volumes_sold,
        'publisher': publisher,
        'genre': genre,
    })
    
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,book_name,author_name,volumes_sold,publisher,genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General


9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [57]:

driver.get('https://www.imdb.com/list/ls095964455/')

In [58]:
all_boxes = driver.find_elements_by_xpath('//div[@class="lister-item-content"]')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [59]:
all_list = []
for one_box in all_boxes:
    
    name = one_box.find_element_by_xpath('.//h3/a').text
    year_span = one_box.find_element_by_xpath('.//h3/span[2]').text
    genre = one_box.find_element_by_xpath('.//p/span[@class="genre"]').text
    run_time = one_box.find_element_by_xpath('.//p/span[@class="runtime"]').text
    ratings = one_box.find_element_by_xpath('.//div[@class="ipl-rating-star small"]').text
    votes = one_box.find_element_by_xpath('.//span[@name="nv"]').text
    
    all_list.append({
        'name': name,
        'year_span': year_span,
        'genre': genre,
        'run_time': run_time,
        'ratings': ratings,
        'votes': votes,
    })
    
    
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:392: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

,name,year_span,genre,run_time,ratings,votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,882,499"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"915,869"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"904,312"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"270,910"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,306"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,899"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,771"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,337"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,886"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"203,698"


10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year ##### Note: - from the home page you have to go to the Show All Dataset page through code

In [60]:
driver.get('https://archive.ics.uci.edu/')

In [61]:
driver.find_element_by_xpath('//b').click()

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [62]:
all_boxes = driver.find_elements_by_xpath('//table[@cellpadding="5" and @border="1"]/tbody/tr')

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

In [63]:
all_list = []
for i, one_box in enumerate(all_boxes):
    
    # Skiping Column
    
    if i == 0:
        continue
        
    dataset_name = one_box.find_elements_by_xpath('.//td')[0].text
    data_type = one_box.find_elements_by_xpath('.//td')[1].text
    task = one_box.find_elements_by_xpath('.//td')[2].text
    attribute_type = one_box.find_elements_by_xpath('.//td')[3].text
    no_of_instances = one_box.find_elements_by_xpath('.//td')[4].text
    no_of_attribute = one_box.find_elements_by_xpath('.//td')[5].text
    year = one_box.find_elements_by_xpath('.//td')[6].text


    
    all_list.append({
        'dataset_name':dataset_name ,
        'data_type':data_type ,
        'task':task ,
        'attribute_type':attribute_type ,
        'no_of_instances':no_of_instances ,
        'no_of_attribute':no_of_attribute ,
        'year':year ,
    })
    
    
df = pd.DataFrame(all_list)
df

C:\Users\dell\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:425: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,dataset_name,data_type,task,attribute_type,no_of_instances,no_of_attribute,year
0,Abalone,,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177
1,Adult,,Adult,Multivariate,Classification,"Categorical, Integer",48842
2,Annealing,,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798
3,Anonymous Microsoft Web Data,,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711
4,Arrhythmia,,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,,in-vehicle coupon recommendation,Multivariate,Classification,,12684
584,Gait Classification,,Gait Classification,Multivariate,Classification,Real,48
585,Wikipedia Math Essentials,,Wikipedia Math Essentials,Time-Series,Regression,Real,731
586,Wikipedia Math Essentials,,Wikipedia Math Essentials,Time-Series,Regression,Real,731
587,Synchronous Machine Data Set,,Synchronous Machine Data Set,Multivariate,Regression,Real,557